import os
from fpdf import FPDF
from datetime import datetime
from backend.config import Config


class ApolloMetricsPDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 16)
        self.set_text_color(108, 99, 255)
        self.cell(0, 10, 'Apollo Metrics', 0, 1, 'C')
        self.set_font('Arial', 'I', 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 6, 'AI-Powered Data Analysis Report', 0, 1, 'C')
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()}/{{nb}}', 0, 0, 'C')

    def section_title(self, title):
        self.set_font('Arial', 'B', 13)
        self.set_text_color(108, 99, 255)
        self.cell(0, 10, title, 0, 1, 'L')
        self.set_draw_color(108, 99, 255)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(3)

    def sub_section(self, text):
        self.set_font('Arial', 'B', 11)
        self.set_text_color(50, 50, 50)
        self.cell(0, 8, text, 0, 1, 'L')
        self.ln(1)

    def body_text(self, text):
        self.set_font('Arial', '', 10)
        self.set_text_color(50, 50, 50)
        self.multi_cell(0, 6, text)
        self.ln(2)

    def add_stat_row(self, label, value):
        self.set_font('Arial', '', 10)
        self.set_text_color(50, 50, 50)
        self.cell(80, 7, label, 0, 0)
        self.set_font('Arial', 'B', 10)
        self.cell(0, 7, str(value), 0, 1)


def generate_report(user_name, dataset_name, dataset_summary, cleaning_summary,
                    eda_results, ml_results, llm_explanation, recommendations, report_name):
    config = Config()
    pdf = ApolloMetricsPDF()
    pdf.alias_nb_pages()
    pdf.add_page()

    pdf.ln(5)
    pdf.set_font('Arial', '', 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 7, f'Generated for: {user_name}', 0, 1)
    pdf.cell(0, 7, f'Dataset: {dataset_name}', 0, 1)
    pdf.cell(0, 7, f'Date: {datetime.now().strftime("%B %d, %Y %H:%M")}', 0, 1)
    pdf.ln(5)

    pdf.section_title('1. Dataset Overview')
    if dataset_summary:
        for key, value in dataset_summary.items():
            if isinstance(value, (int, float, str)):
                pdf.add_stat_row(key.replace('_', ' ').title(), value)
        pdf.ln(3)

    if cleaning_summary:
        pdf.section_title('2. Data Cleaning Summary')
        for key, value in cleaning_summary.items():
            if isinstance(value, (int, float, str)):
                pdf.add_stat_row(key.replace('_', ' ').title(), value)
        pdf.ln(3)

    if eda_results:
        pdf.section_title('3. EDA Insights')
        insights = eda_results.get('insights', [])
        if insights:
            for insight in insights[:10]:
                pdf.body_text(f'- {insight}')

        missing_report = eda_results.get('missing_report', {})
        if missing_report:
            pdf.sub_section('Missing Value Report')
            for col, info in missing_report.items():
                pdf.body_text(f"- {col}: {info.get('missing_count', 0)} missing ({info.get('missing_percentage', 0)}%)")

    if ml_results:
        pdf.section_title('4. Machine Learning Results')
        pdf.body_text(f"Task Type: {ml_results.get('task_type', 'N/A')}")
        pdf.body_text(f"Target Column: {ml_results.get('target_column', 'N/A')}")
        pdf.body_text(f"Best Model: {ml_results.get('best_model', 'N/A')}")
        pdf.body_text(f"Best Score: {ml_results.get('best_score', 'N/A')}")

        all_results = ml_results.get('all_results', {})
        if all_results:
            for model_name, result in all_results.items():
                if 'metrics' in result:
                    pdf.sub_section(f'{model_name}')
                    for metric, value in result['metrics'].items():
                        pdf.body_text(f"  {metric}: {value}")

    if llm_explanation:
        pdf.section_title('5. AI-Generated Explanation')
        pdf.body_text(llm_explanation)

    if recommendations:
        pdf.section_title('6. Business Recommendations')
        pdf.body_text(recommendations)

    pdf.section_title('7. Disclaimer')
    pdf.body_text('This report was automatically generated by Apollo Metrics. The insights and recommendations are based on the provided dataset and may require human expert review before making business decisions.')

    report_path = os.path.join(config.REPORTS_FOLDER, f"{report_name}.pdf")
    pdf.output(report_path)
    return report_path
